config/routes.rb
Rails.application.routes.draw do

  resources :products
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resource :cart, only: [:show] do
  post 'add_item/:product_id', to: 'carts#add_item', as: 'add_item'
  delete 'remove_item/:product_id', to: 'carts#remove_item', as: 'remove_item'
  delete 'empty', to: 'carts#empty', as: 'empty'
  post 'increase_item/:product_id', to: 'carts#increase_item', as: 'increase_item'
  post 'decrease_item/:product_id', to: 'carts#decrease_item', as: 'decrease_item'
end

  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
    validates :quantity, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
 
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_many :cart_items
  has_many :carts, through: :cart_items

  mount_uploader :image, ImageUploader
  serialize :image, JSON # If you use SQLite, add this line

  validates :title, :brand, :price, :model, presence: true
  # Set max lenght to the description, price and title 
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
  validates :price, length: { maximum: 10 }

  # You can input more brands finish and condition here
  BRAND = %w{ Ferrari Opel Lenovo Fossil}
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :products, dependent: :destroy
         has_one :cart, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CurrentCart

  before_action :transfer_guest_cart, if: :user_signed_in?

  private

  def transfer_guest_cart
    return unless session[:cart_id] && current_cart.cart_items.empty?

    guest_cart = Cart.find(session[:cart_id])
    guest_cart.cart_items.each do |item|
      current_cart.cart_items.create(product: item.product, quantity: item.quantity)
    end
    guest_cart.destroy
    session[:cart_id] = nil
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_product, only: [:add_item, :remove_item]

  def show
    @cart_items = current_cart.cart_items.includes(:product)
  end

  def add_item
    @cart_item = current_cart.cart_items.find_or_initialize_by(product: @product)
    @cart_item.quantity ||= 0
    @cart_item.quantity += 1
    @cart_item.save
    flash[:notice] = "Added to your cart"
    redirect_to cart_path
  end

  def remove_item
    @cart_item = current_cart.cart_items.find_by(product: @product)
    @cart_item&.destroy
    flash[:notice] = "Removed from your cart"
    redirect_to cart_path
  end

  def empty
    current_cart.cart_items.destroy_all
    flash[:notice] = "Your cart is now empty"
    redirect_to root_path
  end
  def increase_item
  item = current_cart.cart_items.find_by(product_id: params[:product_id])
  if item
    item.quantity += 1
    item.save
  end
  redirect_to cart_path
end

def decrease_item
  item = current_cart.cart_items.find_by(product_id: params[:product_id])
  if item
    item.quantity -= 1
    if item.quantity <= 0
      item.destroy
    else
      item.save
    end
  end
  redirect_to cart_path
end


  private

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  included do
  helper_method :current_cart
end


  private

def current_cart
  if user_signed_in?
    @current_cart ||= current_user.cart || current_user.create_cart
  else
    @current_cart ||= Cart.find_by(id: session[:cart_id])
    unless @current_cart
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]
  
  before_action :authenticate_user!, except: [:index, :show]


  # GET /products or /products.json
  def index
    @products = Product.all.order("created_at desc")
  end

  # GET /products/1 or /products/1.json
  def show
    @products = Product.find(params[:id])
  end

  def find_product_by_id(id)
    connection.execute("SELECT * FROM products WHERE products.id = ? LIMIT 1", id).first
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

 # DELETE /products/1 or /products/1.json
def destroy
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image)
    end
end

app/controllers/registrations_controller.rb
# This must be implemented.
# sign_up_params and account_update_params
class RegistrationsController < Devise::RegistrationsController

 private
   # Parameters allowed during sign up
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
   def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  end

app/helpers/products_helper.rb
module ProductsHelper
  def product_author(product)
        user_signed_in? && current_user == product.user
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/add_item.html.erb
<h1>Carts#add_item</h1>
<p>Find me in app/views/carts/add_item.html.erb</p>

app/views/carts/empty.html.erb
<h1>Carts#empty</h1>
<p>Find me in app/views/carts/empty.html.erb</p>

app/views/carts/remove_item.html.erb
<h1>Carts#remove_item</h1>
<p>Find me in app/views/carts/remove_item.html.erb</p>

app/views/carts/show.html.erb
<section class="section">
  <div class="container">
    <h2 class="title is-3 mb-5">Your Cart</h2>

    <% if @cart_items.any? %>
      <table class="table is-fullwidth is-striped is-hoverable">
        <thead>
          <tr>
            <th>Product</th>
            <th class="has-text-centered">Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |item| %>
            <tr>
              <td><%= item.product.title %></td>
              <td class="has-text-centered">
                <div class="buttons has-addons is-centered">
                  <%= button_to '+', increase_item_cart_path(item.product), method: :post, class: "button is-small" %>
                  <span class="button is-static is-small"><%= item.quantity %></span>
                  <%= button_to '-', decrease_item_cart_path(item.product), method: :post, class: "button is-small" %>
                </div>
              </td>
              <td><%= number_to_currency(item.product.price) %></td>
              <td><%= number_to_currency(item.product.price * item.quantity) %></td>
              <td>
                <%= link_to "Remove", remove_item_cart_path(item.product), method: :delete, class: "button is-small is-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="has-text-right mt-4">
        <p class="is-size-5"><strong>Total:</strong> <%= number_to_currency(@cart_items.sum { |item| item.product.price * item.quantity }) %></p>

        <%= button_to 'Empty Cart', empty_cart_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger mt-2" %>
      </div>
    <% else %>
      <p class="has-text-grey">Your cart is empty.</p>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Shop</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
  <!-- Cart Link -->
          <%= link_to cart_path, class: "button is-light is-rounded" do %>
            <span class="icon">
              <i class="fas fa-shopping-cart"></i>
            </span>
            <span>Cart (<%= current_cart.cart_items.count %>)</span>
          <% end %>

            <% if user_signed_in? %>
              <%= link_to 'Sell', new_product_path, class: "navbar-item button is-dark" %>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>

app/views/products/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @product, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Brand</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Product::BRAND, prompt: "Select brand" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Finish</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Product::FINISH, prompt: "Select finish" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Product::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input product-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', products_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Product
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse new products
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="product-index-grid pt4">
  <% @products.each do |product| %>

    <div class="product border-light">
      <div class="product-thumb">
      <%= link_to image_tag(product.image_url(:thumb)), product %>
      <% if product.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= product.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to product.title, product %></h3>

      <p class="has-text-gray fg pt1">Sold by: <%= product.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(product.price) %></p>

<% if user_signed_in? && current_user == product.user %>
  <%= link_to 'Edit', edit_product_path(product), class: "button is-small" %>
  <%= link_to 'Delete', product, method: :delete, data: { confirm: "Are you sure?" }, class: "button is-small" %>
<% end %>


    </div>
  </div>
  <% end %>
</div>

app/views/products/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       Sell a Product
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section product-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @product.title %></h1>

      <ul class="pv1">
        <% if @product.brand? %>
        <li class="inline-block pr3"><%= @product.brand %></li>
        <% end %>

        <li class="inline-block pr3"><%= @product.model %></li>

        <% if @product.condition? %>
        <li class="inline-block pr3"><%= @product.condition %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@product.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @product.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @product.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @product.condition %></td>
        </tr>
        <% end %>

        <% if @product.finish %>
          <tr>
            <td class="has-text-weight-bold">Finish:</td>
            <td><%= @product.finish %></td>
          </tr>
        <% end %>

        <% if @product.brand %>
          <tr>
            <td class="has-text-weight-bold">Brand:</td>
            <td><%= @product.brand %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Model:</td>
          <td><%= @product.model %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@product.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @product.user.name %></p>
         <%= button_to "Add to Cart", add_item_cart_path(@product), method: :post, class: "button is-primary is-fullwidth" %>
      </div>
    </div>
  </div>

</section>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>